### ISSUE TITLE
Cannot install package luci-i18n-homeproxy-zh-cn

### ISSUE THREAD

**Issue by Yumega** [lxiaya/openwrt-homeproxy#4]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-netlink-diag for sing-box
 * pkg_hash_check_unresolved: cannot find dependency firewall4 for luci-app-homeproxy
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-tproxy for luci-app-homeproxy
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-homeproxy found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-homeproxy.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-homeproxy-zh-cn:
 *      kmod-netlink-diag
 *      firewall4
 *      kmod-nft-tproxy
 * opkg_install_cmd: Cannot install package luci-i18n-homeproxy-zh-cn.

**Comment by lxiaya** [comment]
Follow the prompts to install dependencies, or pull the source code and compile it yourself.
