### ISSUE TITLE
the subscription is not being updated in an unencrypted form

### ISSUE THREAD

**Issue by shep-k-a** [lxiaya/openwrt-homeproxy#5]
the subscription is not being updated in an unencrypted form.
I tried any option of "Default packed encoding" with "Allow insecure" enabled and disabled, but it did not give any result. The subscription simply does not appear when updating.
The subscription is taken from the 3x-ui panel. 
If the subscription is encrypted, everything works fine

**Comment by lxiaya** [comment]
Please subscribe by sing-box standard.
